version: "3"

services:

  springbootdemo:
    image: ${DOCKER_REGISTRY}/docker-demo/springbootondocker
    build: .
    ports:
      - "8082:8080"
    networks:
      - demo-network
    depends_on:
      - demodb
    links:
      - demodb
  demodb:
    image: postgres:9.4
    restart: always
    container_name: demodb
    ports:
      - "5432:5432"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER:'demouser'
      - POSTGRES_PASSWORD:'demopwd'
      - POSTGRES_DB:'mydemodb'
    ports:
      - '5432:5432'
    networks:
      - demo-network

volumes:
  db-data:

networks:
  demo-network:
